config/routes.rb
Rails.application.routes.draw do
  resources :tipo_productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tipo_producto.rb
class TipoProducto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tipo_productos_controller.rb
class TipoProductosController < ApplicationController
  before_action :set_tipo_producto, only: [:show, :edit, :update, :destroy]

  # GET /tipo_productos
  # GET /tipo_productos.json
  def index
    @tipo_productos = TipoProducto.all
  end

  # GET /tipo_productos/1
  # GET /tipo_productos/1.json
  def show
  end

  # GET /tipo_productos/new
  def new
    @tipo_producto = TipoProducto.new
  end

  # GET /tipo_productos/1/edit
  def edit
  end

  # POST /tipo_productos
  # POST /tipo_productos.json
  def create
    @tipo_producto = TipoProducto.new(tipo_producto_params)

    respond_to do |format|
      if @tipo_producto.save
        format.html { redirect_to @tipo_producto, notice: 'Tipo producto was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_producto }
      else
        format.html { render :new }
        format.json { render json: @tipo_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_productos/1
  # PATCH/PUT /tipo_productos/1.json
  def update
    respond_to do |format|
      if @tipo_producto.update(tipo_producto_params)
        format.html { redirect_to @tipo_producto, notice: 'Tipo producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_producto }
      else
        format.html { render :edit }
        format.json { render json: @tipo_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_productos/1
  # DELETE /tipo_productos/1.json
  def destroy
    @tipo_producto.destroy
    respond_to do |format|
      format.html { redirect_to tipo_productos_url, notice: 'Tipo producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_producto
      @tipo_producto = TipoProducto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_producto_params
      params.require(:tipo_producto).permit(:tipoProdNombre, :tipoProdDesc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tipo_productos_helper.rb
module TipoProductosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppEGO</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tipo_productos/_form.html.erb
<%= form_for(tipo_producto) do |f| %>
  <% if tipo_producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_producto.errors.count, "error") %> prohibited this tipo_producto from being saved:</h2>

      <ul>
      <% tipo_producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipoProdNombre %>
    <%= f.text_field :tipoProdNombre %>
  </div>

  <div class="field">
    <%= f.label :tipoProdDesc %>
    <%= f.text_area :tipoProdDesc %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_productos/edit.html.erb
<h1>Editing Tipo Producto</h1>

<%= render 'form', tipo_producto: @tipo_producto %>

<%= link_to 'Show', @tipo_producto %> |
<%= link_to 'Back', tipo_productos_path %>

app/views/tipo_productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Productos</h1>

<table>
  <thead>
    <tr>
      <th>Tipoprodnombre</th>
      <th>Tipoproddesc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_productos.each do |tipo_producto| %>
      <tr>
        <td><%= tipo_producto.tipoProdNombre %></td>
        <td><%= tipo_producto.tipoProdDesc %></td>
        <td><%= link_to 'Show', tipo_producto %></td>
        <td><%= link_to 'Edit', edit_tipo_producto_path(tipo_producto) %></td>
        <td><%= link_to 'Destroy', tipo_producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Producto', new_tipo_producto_path %>

app/views/tipo_productos/new.html.erb
<h1>New Tipo Producto</h1>

<%= render 'form', tipo_producto: @tipo_producto %>

<%= link_to 'Back', tipo_productos_path %>

app/views/tipo_productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipoprodnombre:</strong>
  <%= @tipo_producto.tipoProdNombre %>
</p>

<p>
  <strong>Tipoproddesc:</strong>
  <%= @tipo_producto.tipoProdDesc %>
</p>

<%= link_to 'Edit', edit_tipo_producto_path(@tipo_producto) %> |
<%= link_to 'Back', tipo_productos_path %>